init:
	make init -C core
	make init -C couchdb

build:
	make build -C core
	make build -C couchdb

deploy:
	make deploy -C core
	make deploy -C couchdb

set-dev-version:
	make set-dev-version -C core
	make set-dev-version -C couchdb

set-release-version:
	make set-release-version -C core
	make set-release-version -C couchdb
