init:
	npm install -g grunt-cli
	make init -C core
	make init -C generator

build:
	make build -C core
	make build -C generator

deploy:
	make deploy -C core
	make deploy -C generator

set-dev-version:
	make set-dev-version -C core
	make set-dev-version -C generator

set-release-version:
	make set-release-version -C core
	make set-release-version -C generator
